name: Build Workflow

on:
  push:
    branches: [ main ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        # This forces pnpm to install in the root, ignoring potential workspace settings
        run: pnpm install --no-frozen-lockfile --workspace-root

      - name: Build project
        run: pnpm build
