name: "Deploy Now: Build and Deploy"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build

      - name: Deploy
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: a0e14c30-722a-440a-a431-9929ba78cf3b
          branch-id: main
          folder: .next/standalone
